### ISSUE TITLE
Crash while running rexray volume ls for first time

### ISSUE THREAD

**Issue by harshavardhana** [codedellemc/rexray#1041]
```
Oops, an error occured!

  libstorage: invalid format

To correct the error please review:

  - Debug output by using the flag -l debug
  - The REX-ray website at https://github.com/codedellemc/rexray
  - The on↓ine he↓p be↓ow

List volumes

Usage: 
  rexray volume ls [flags] [flags]

Aliases:
  ls, l, list, get, inspect

Examples:
rexray volume ls [OPTIONS] [VOLUME...]

Flags:
      --attached    A flag that indicates only volumes attached to this host should be returned
      --available   A flag that indicates only available volumes should be returned
      --path        A flag that indicates only volumes attached to this host should be returned, along with their path info

Global Flags:
  -c, --config string     The path to a custom REX-Ray configuration file
  -n, --dryRun            Show what action(s) will occur, but do not execute them
  -f, --format string     The output format (tmpl, json, jsonp) (default "tmpl")
  -?, --help              Help about the current command
  -h, --host string       The libStorage host.
  -l, --logLevel string   The log level (error, warn, info, debug) (default "warn")
  -q, --quiet             Suppress table headers
  -s, --service string    The libStorage service.
      --template string   The Go template to use when --format is set to 'tmpl'
      --templateTabs      Set to true to use a Go tab writer with the output template (default true)
  -v, --verbose           Print verbose help information

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x17f52be]

goroutine 1 [running]:
github.com/codedellemc/rexray/cli.(*CLI).lsVolumes(0xc42009a000, 0x3310320, 0x0, 0x0, 0x1, 0xc420088378, 0xc4204a1998, 0x15be7c6)
	/go/src/github.com/codedellemc/rexray/cli/cmds_10_volume.go:856 +0x3e
github.com/codedellemc/rexray/cli.(*CLI).initVolumeCmds.func2(0xc420093680, 0x3310320, 0x0, 0x0)
	/go/src/github.com/codedellemc/rexray/cli/cmds_10_volume.go:53 +0x720
github.com/codedellemc/rexray/vendor/github.com/spf13/cobra.(*Command).execute(0xc420093680, 0x3310320, 0x0, 0x0, 0xc420093680, 0x3310320)
	/go/src/github.com/codedellemc/rexray/vendor/github.com/spf13/cobra/command.go:654 +0x299
github.com/codedellemc/rexray/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42017a480, 0xc4204a1c48, 0xc4204a1c40, 0xc42001aa40)
	/go/src/github.com/codedellemc/rexray/vendor/github.com/spf13/cobra/command.go:729 +0x339
github.com/codedellemc/rexray/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42017a480, 0x263ce68, 0xc42009a000)
	/go/src/github.com/codedellemc/rexray/vendor/github.com/spf13/cobra/command.go:688 +0x2b
github.com/codedellemc/rexray/cli.(*CLI).Execute(0xc42009a000)
	/go/src/github.com/codedellemc/rexray/cli/cli.go:246 +0x55
github.com/codedellemc/rexray/cli.Execute(0x3283de0, 0xc42033f260, 0x0, 0x0)
	/go/src/github.com/codedellemc/rexray/cli/cli.go:229 +0x57
main.main()
	/go/src/github.com/codedellemc/rexray/rexray.go:188 +0x7d6
```
This section is for issues that relate to discovered problems or bugs.

## Version

```shell
 rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.10.2
OsArch: Linux-x86_64
Commit: 4c451f856336c83680cc250ff62998bc70876c40
Formed: Tue, 12 Sep 2017 14:18:02 PDT
```

## Expected Behavior
No crash should occur.

## Actual Behavior
Crash observed.

## Steps To Reproduce
Perhaps just install rexray for the first time and run `rexray volume ls` ?

Here is the debugging output

```
DEBU[0000] trapped signals                               time=1506235849602
DEBU[0000] loading config                                buildType=client+agent+controller configFileName=rexray globalConfigFileExists=false globalConfigFilePath=/home/harsha/.rexray/etc/rexray.yml ignoreExists=false time=1506235849602 userConfigFileExists=false userConfigFilePath=/home/harsha/.rexray/rexray.yml
DEBU[0000] cannot find global or user file               buildType=client+agent+controller configFileName=rexray globalConfigFileExists=false globalConfigFilePath=/home/harsha/.rexray/etc/rexray.yml ignoreExists=false time=1506235849602 userConfigFileExists=false userConfigFilePath=/home/harsha/.rexray/rexray.yml
DEBU[0000] loading config                                buildType=client+agent+controller configFileName=config globalConfigFileExists=false globalConfigFilePath=/home/harsha/.rexray/etc/config.yml ignoreExists=true time=1506235849602 userConfigFileExists=false userConfigFilePath=/home/harsha/.rexray/config.yml
DEBU[0000] disabled config file exist check              buildType=client+agent+controller configFileName=config globalConfigFileExists=false globalConfigFilePath=/home/harsha/.rexray/etc/config.yml ignoreExists=true time=1506235849602 userConfigFileExists=false userConfigFilePath=/home/harsha/.rexray/config.yml
DEBU[0000] created new config                            buildType=client+agent+controller configFileName=config globalConfigFileExists=false globalConfigFilePath=/home/harsha/.rexray/etc/config.yml ignoreExists=true time=1506235849602 userConfigFileExists=false userConfigFilePath=/home/harsha/.rexray/config.yml
DEBU[0000] initializing configuration                   
DEBU[0000] loading yaml for Global                      
DEBU[0000] loading yaml for Docker                      
DEBU[0000] usage template path                           path=/home/harsha/.rexray/usage.template time=1506235849605
DEBU[0000] loaded usage template                         source=UsageTemplate time=1506235849605
DEBU[0000] updating log level                            level=debug time=1506235849606
INFO[0000] updated log level                             logLevel=debug
DEBU[0000] created scoped scope                          new=rexray.cli parentScopes=rexray,
DEBU[0000] os.args                                       time=1506235849611 val=[rexray volume ls -l debug]
DEBU[0000] activating libStorage                         cmd=ls time=1506235849611
DEBU[0000] host is empty; initiliazing default services  time=1506235849623
DEBU[0000] libStorage auto service mode disabled; service name empty  time=1506235849627
DEBU[0000] starting embedded libStorage server           time=1506235849627
DEBU[0000] created scoped scope                          new=libstorage.server parentScopes=rexray.cli,rexray,
INFO[0000] configured logging                            libstorage.logging.httpRequests=false libstorage.logging.httpResponses=false libstorage.logging.level=debug server=psychadelic-catcher-ua time=1506235849690
DEBU[0000] parsed server auth property                   libstorage.server.auth.disabled=false server=psychadelic-catcher-ua time=1506235849708
DEBU[0000] parsed server auth property                   libstorage.server.auth.key= server=psychadelic-catcher-ua time=1506235849721
DEBU[0000] parsed server auth property                   libstorage.server.auth.alg=HS256 server=psychadelic-catcher-ua time=1506235849730
DEBU[0000] parsed server auth property                   libstorage.server.auth.allow=[] server=psychadelic-catcher-ua time=1506235849743
DEBU[0000] parsed server auth property                   libstorage.server.auth.deny=[] server=psychadelic-catcher-ua time=1506235849754
INFO[0000] configured global auth                        libstorage.server.auth.alg=HS256 libstorage.server.auth.allow=[] libstorage.server.auth.deny=[] libstorage.server.auth.disabled=false libstorage.server.auth.key= server=psychadelic-catcher-ua time=1506235849754
INFO[0000] initializing server                           server=psychadelic-catcher-ua time=1506235849754
INFO[0000] initializing server services                  server=psychadelic-catcher-ua time=1506235849755
DEBU[0000] configured result schema validation           enabled=false server=psychadelic-catcher-ua time=1506235849759
Oops, an error occured!

  libstorage: invalid format

To correct the error please review:

  - Debug output by using the flag -l debug
  - The REX-ray website at https://github.com/codedellemc/rexray
  - The on↓ine he↓p be↓ow

List volumes

Usage: 
  rexray volume ls [flags] [flags]

Aliases:
  ls, l, list, get, inspect

Examples:
rexray volume ls [OPTIONS] [VOLUME...]

Flags:
      --attached    A flag that indicates only volumes attached to this host should be returned
      --available   A flag that indicates only available volumes should be returned
      --path        A flag that indicates only volumes attached to this host should be returned, along with their path info

Global Flags:
  -c, --config string     The path to a custom REX-Ray configuration file
  -n, --dryRun            Show what action(s) will occur, but do not execute them
  -f, --format string     The output format (tmpl, json, jsonp) (default "tmpl")
  -?, --help              Help about the current command
  -h, --host string       The libStorage host.
  -l, --logLevel string   The log level (error, warn, info, debug) (default "warn")
  -q, --quiet             Suppress table headers
  -s, --service string    The libStorage service.
      --template string   The Go template to use when --format is set to 'tmpl'
      --templateTabs      Set to true to use a Go tab writer with the output template (default true)
  -v, --verbose           Print verbose help information

DEBU[0000] waiting until libStorage is stopped           time=1506235849783
DEBU[0000] done waiting on err chan; err chan is nil     time=1506235849783
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x17f52be]

goroutine 1 [running]:
github.com/codedellemc/rexray/cli.(*CLI).lsVolumes(0xc4200b2000, 0xc4200e5100, 0x0, 0x2, 0x1, 0xc42026bff0, 0xc4204a7998, 0x15be7c6)
	/go/src/github.com/codedellemc/rexray/cli/cmds_10_volume.go:856 +0x3e
github.com/codedellemc/rexray/cli.(*CLI).initVolumeCmds.func2(0xc4200af680, 0xc4200e5100, 0x0, 0x2)
	/go/src/github.com/codedellemc/rexray/cli/cmds_10_volume.go:53 +0x720
github.com/codedellemc/rexray/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200af680, 0xc4200e50c0, 0x2, 0x2, 0xc4200af680, 0xc4200e50c0)
	/go/src/github.com/codedellemc/rexray/vendor/github.com/spf13/cobra/command.go:654 +0x299
github.com/codedellemc/rexray/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200aa480, 0xc4204a7c48, 0xc4204a7c40, 0xc42001b080)
	/go/src/github.com/codedellemc/rexray/vendor/github.com/spf13/cobra/command.go:729 +0x339
github.com/codedellemc/rexray/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200aa480, 0x263ce68, 0xc4200b2000)
	/go/src/github.com/codedellemc/rexray/vendor/github.com/spf13/cobra/command.go:688 +0x2b
github.com/codedellemc/rexray/cli.(*CLI).Execute(0xc4200b2000)
	/go/src/github.com/codedellemc/rexray/cli/cli.go:246 +0x55
github.com/codedellemc/rexray/cli.Execute(0x3283de0, 0xc42001f2c0, 0x0, 0x0)
	/go/src/github.com/codedellemc/rexray/cli/cli.go:229 +0x57
main.main()
	/go/src/github.com/codedellemc/rexray/rexray.go:188 +0x7d6
```

**Comment by clintkitson** [comment]
Hello @harshavardhana,

It sounds like your config file is incorrectly formatted. Can you post it here?

**Comment by harshavardhana** [comment]
I didn't have one in the first place it was a fresh install. But it shouldn't crash.

**Comment by clintkitson** [comment]
Got it, I agree. We will look into this, thank you.

**Comment by sirsikar-lalit** [comment]
Any update, facing same error.

**Comment by clintkitson** [comment]
Hello @sirsikar-lalit,

I believe the issue is referencing an invalid configuration file that makes this situation occur. It is being looked at for an upcoming release to modify some of the configuration behavior. Are you saying that you can't get it working, or that there should be a more graceful error?

**Comment by Olvikolvi** [comment]
I'am getting same error.. Running rexray on CoreOS 1632.2.1 (Ladybug)
config.yml is like this
```
libstorage:
  service: rbd
rbd:
  defaultPool: rbd
```

```
core@coreos1 ~ $ rexray volume ls -l debug
INFO[0000] configured default CSI module                 CSI_ENDPOINT=/home/core/.rexray/run/docker/plugins/rexray.sock time=1518095671176
INFO[0000] DockerLegacyMode                              enabled=false time=1518095671177
DEBU[0000] trapped signals                               time=1518095671177
DEBU[0000] loading config                                buildType=client+agent+controller configFileName=rexray globalConfigFileExists=false globalConfigFilePath=/home/core/.rexray/etc/rexray.yml ignoreExists=false time=1518095671177 userConfigFileExists=false userConfigFilePath=/home/core/.rexray/rexray.yml
DEBU[0000] cannot find global or user file               buildType=client+agent+controller configFileName=rexray globalConfigFileExists=false globalConfigFilePath=/home/core/.rexray/etc/rexray.yml ignoreExists=false time=1518095671177 userConfigFileExists=false userConfigFilePath=/home/core/.rexray/rexray.yml
DEBU[0000] loading config                                buildType=client+agent+controller configFileName=config globalConfigFileExists=false globalConfigFilePath=/home/core/.rexray/etc/config.yml ignoreExists=true time=1518095671177 userConfigFileExists=false userConfigFilePath=/home/core/.rexray/config.yml
DEBU[0000] disabled config file exist check              buildType=client+agent+controller configFileName=config globalConfigFileExists=false globalConfigFilePath=/home/core/.rexray/etc/config.yml ignoreExists=true time=1518095671177 userConfigFileExists=false userConfigFilePath=/home/core/.rexray/config.yml
DEBU[0000] created new config                            buildType=client+agent+controller configFileName=config globalConfigFileExists=false globalConfigFilePath=/home/core/.rexray/etc/config.yml ignoreExists=true time=1518095671177 userConfigFileExists=false userConfigFilePath=/home/core/.rexray/config.yml
DEBU[0000] initializing configuration                   
DEBU[0000] loading yaml for Global                      
DEBU[0000] loading yaml for CSI                         
DEBU[0000] usage template path                           path=/home/core/.rexray/usage.template time=1518095671179
DEBU[0000] loaded usage template                         source=UsageTemplate time=1518095671179
DEBU[0000] created scoped scope                          new=rexray.cli parentScopes=rexray,
DEBU[0000] updating log level                            level=debug time=1518095671181
INFO[0000] updated log level                             logLevel=debug
DEBU[0000] os.args                                       time=1518095671185 val=[rexray volume ls -l debug]
DEBU[0000] activating libStorage                         cmd=ls time=1518095671187
DEBU[0000] host is empty; initiliazing default services  time=1518095671195
DEBU[0000] libStorage auto service mode disabled; service name empty  time=1518095671198
DEBU[0000] starting embedded libStorage server           time=1518095671198
DEBU[0000] created scoped scope                          new=libstorage.server parentScopes=rexray.cli,rexray,
INFO[0000] configured logging                            libstorage.logging.httpRequests=false libstorage.logging.httpResponses=false libstorage.logging.level=debug server=bevel-whimsey-vg time=1518095671263
DEBU[0000] parsed server auth property                   libstorage.server.auth.disabled=false server=bevel-whimsey-vg time=1518095671283
DEBU[0000] parsed server auth property                   libstorage.server.auth.key= server=bevel-whimsey-vg time=1518095671291
DEBU[0000] parsed server auth property                   libstorage.server.auth.alg=HS256 server=bevel-whimsey-vg time=1518095671302
DEBU[0000] parsed server auth property                   libstorage.server.auth.allow=[] server=bevel-whimsey-vg time=1518095671311
DEBU[0000] parsed server auth property                   libstorage.server.auth.deny=[] server=bevel-whimsey-vg time=1518095671327
INFO[0000] configured global auth                        libstorage.server.auth.alg=HS256 libstorage.server.auth.allow=[] libstorage.server.auth.deny=[] libstorage.server.auth.disabled=false libstorage.server.auth.key= server=bevel-whimsey-vg time=1518095671327
INFO[0000] initializing server                           server=bevel-whimsey-vg time=1518095671327
INFO[0000] initializing server services                  server=bevel-whimsey-vg time=1518095671327
DEBU[0000] configured result schema validation           enabled=false server=bevel-whimsey-vg time=1518095671330
Oops, an error occured!

  libstorage: invalid format

```

**Comment by Olvikolvi** [comment]
Figured it out.. config.yml needs to be in /home/core/.rexray/ folder not in /etc/rexray/

**Comment by dradux** [comment]
@Olvikolvi I'm not sure I would recommend putting the config file in a specific user's home directory.

The issue appears to be that there is no config file added/set by default. Here's the steps I used to get `rexray volume ls` to work directly after a fresh install:

- install rexray (I installed via curl with `curl -sSL https://rexray.io/install | sh -s -- stable`
- go to https://rexrayconfig.cfapps.io/ and generate a config file (I used AWS/S3FS)
- paste the config file genrated into the `/etc/rexray/config.yml` file
- run `rexray volume ls`
- I now get a list of my buckets

I'm not sure if this can be 'fixed' in the installer as I dont know how the installer could know the config you want. I would suggest updating the install page (https://rexray.readthedocs.io/en/stable/user-guide/installation/) with instructions after the install to proceed to setup the configuration before running a `rexray volume ls`

**Comment by harshavardhana** [comment]
> I'm not sure if this can be 'fixed' in the installer as I dont know how the installer could know the config 

It can indicate as `config.yml` doesn't exist or is not valid? rather than crashing?

**Comment by dradux** [comment]
That sounds good, a general check when running rexray to catch if config file does not exist or has no usable Services defined would be nice.

**Comment by DevopsDood** [comment]
Fresh install crashes with this error. Maybe a default config file would be good?
