### ISSUE TITLE
Can't run Rexray on Openstack Magnum

### ISSUE THREAD

**Issue by duhow** [codedellemc/rexray#1082]
# Summary
Deploying a Docker Swarm Cluster with Openstack (Magnum + Heat), Rexray is not starting.

## Version
```shell
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.8.1+3+dirty
OsArch: Linux-x86_64
Branch: master
Commit: 229368ec1d7e5855a3d38b1838479960bcd63234
Formed: Mon, 06 Mar 2017 14:21:16 UTC
libStorage
----------
SemVer: 0.5.1+339
OsArch: Linux-x86_64
Branch: ea8c47b
Commit: ea8c47bb7896e8ec932781a79419a66848412d73
Formed: Mon, 06 Mar 2017 14:20:50 UTC
```
## Details
Running Magnum 4.1.3 and Heat 8.0.3.
When creating a Docker Swarm cluster via Magnum, with the Rexray driver option selected, Rexray is started while deploying the nodes, but it stops running **(exit code 2)**
Deploy is using the **Docker Image** `openstackmagnum/rexray:alpine`.
Settings are passed by Heat, so config should be fine.

## Logs
```
time="2017-10-23T09:48:29Z" level=info msg="created pid file" pid=2333 time=1508752109818                                                                                                      
time="2017-10-23T09:48:29Z" level=info msg="libStorage auto service mode enabled" driver=openstack time=1508752109841                                                                          
time="2017-10-23T09:48:29Z" level=info msg="configured logging" libstorage.logging.httpRequests=false libstorage.logging.httpResponses=false libstorage.logging.level=info server=citrine-bone-wf time=1508752109891                                                                                                                                                                          
time="2017-10-23T09:48:29Z" level=info msg="initializing server" server=citrine-bone-wf time=1508752109891                                                                                     
time="2017-10-23T09:48:29Z" level=info msg="initializing default endpoint" autoEndpointMode=unix server=citrine-bone-wf time=1508752109902                                                     
time="2017-10-23T09:48:29Z" level=info msg="initializing auto unix endpoint" endpoint=libstorage.server.endpoints.localhost server=citrine-bone-wf time=1508752109910                          
time="2017-10-23T09:48:29Z" level=info msg="configured endpoint" address="unix:///var/run/libstorage/657061279.sock" endpoint=localhost server=citrine-bone-wf time=1508752109923              
time="2017-10-23T09:48:29Z" level=info msg="server created" server=citrine-bone-wf time=1508752109924                                                                                          
time="2017-10-23T09:48:29Z" level=info msg="initialized endpoints" server=citrine-bone-wf time=1508752109924                                                                                   
time="2017-10-23T09:48:29Z" level=info msg="initializing server services" server=citrine-bone-wf time=1508752109924                                                                            
time="2017-10-23T09:48:30Z" level=panic msg="reflect: call of reflect.Value.Elem on struct Value"                                                                                              
panic: reflect: call of reflect.Value.Elem on struct Value [recovered]                                                                                                                         
        panic: reflect: call of reflect.Value.Elem on struct Value [recovered]                 
        panic: reflect: call of reflect.Value.Elem on struct Value [recovered]                                                                                                                 
        panic: (*logrus.Entry) (0x1505000,0xc420198b40)                                        
goroutine 1 [running]:                                                                         
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.Entry.log(0xc420050d00, 0xc4205ec8a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12d4800, 0xc420198b00, ...)                              
        /go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/entry.go:113 +0x28c                                                                                            
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc4226422a8, 0xc422642388, 0x1, 0x1)                                                                           
        /go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/entry.go:169 +0x14b                                                                                            
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.(*Logger).Panic(0xc420050d00, 0xc422642388, 0x1, 0x1)                                                                          
        /go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/logger.go:163 +0xc7                                                                                            
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.Panic(0xc422642388, 0x1, 0x1)                                                                                                  
        /go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/exported.go:107 +0x4b                                                                                          
github.com/codedellemc/rexray/cli/cli.(*CLI).Execute.func2()                                                                                                                                   
        /go/src/github.com/codedellemc/rexray/cli/cli/cli.go:227 +0xf8                         
panic(0x12d4820, 0xc42010f3e0)                                                                 
        /usr/local/go/src/runtime/panic.go:489 +0x2cf                                          
github.com/codedellemc/rexray/cli/cli.(*CLI).execute.func1()                                   
        /go/src/github.com/codedellemc/rexray/cli/cli/cli.go:247 +0xa8                         
panic(0x12d4820, 0xc42010f3e0)                                                                 
        /usr/local/go/src/runtime/panic.go:489 +0x2cf                                          
github.com/codedellemc/rexray/cli/cli.(*CLI).startDaemon.func1()
        /go/src/github.com/codedellemc/rexray/cli/cli/service.go:187 +0x82
panic(0x12d4820, 0xc42010f3e0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
reflect.Value.Elem(0x1413580, 0xc42010f300, 0x99, 0xc42010f300, 0x99, 0xc422642780)
        /usr/local/go/src/reflect/value.go:746 +0x123
github.com/codedellemc/rexray/vendor/github.com/akutz/golf.fore(0xc42010f360, 0x15, 0x1413580, 0xc42010f300, 0xc4205ec810)
        /go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/golf.go:170 +0x539
github.com/codedellemc/rexray/vendor/github.com/akutz/golf.fore(0xc420356610, 0xb, 0x130ed40, 0xc42010f180, 0xc4205ec810)
        /go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/golf.go:215 +0x3bb
github.com/codedellemc/rexray/vendor/github.com/akutz/golf.fore(0x15357ef, 0x5, 0x14c9f80, 0xc42010f1c0, 0xc4205ec810)
        /go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/golf.go:215 +0x3bb
github.com/codedellemc/rexray/vendor/github.com/akutz/golf.Fore(0x15357ef, 0x5, 0x14c9f80, 0xc42010f1c0, 0xc42010f1c0)
        /go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/golf.go:146 +0xbb
github.com/codedellemc/rexray/vendor/github.com/akutz/golf/logrus.(*TextFormatter).appendKeyValue(0xc420293300, 0xc420127b20, 0x15357ef, 0x5, 0x14c9f80, 0xc42010f1c0)
        /go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/logrus/text_formatter.go:176 +0xaa
github.com/codedellemc/rexray/vendor/github.com/akutz/golf/logrus.(*TextFormatter).Format(0xc420293300, 0xc420198a80, 0x0, 0xc4226431c0, 0x73f9ee, 0x136c980, 0xc420013a10)
        /go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/logrus/text_formatter.go:89 +0x481
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.(*Entry).Reader(0xc420198a80, 0xc40f12ca02, 0xc420198a80, 0x0)
        /go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/entry.go:44 +0x40
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.Entry.log(0xc420050d00, 0xc4205ec7b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5000102, 0xc42010f200, ...)
```

**Comment by clintkitson** [comment]
Can you try the rexray/openstack image instead?

**Comment by duhow** [comment]
@clintkitson That image does not exist.

**Comment by clintkitson** [comment]
Apologies, rexray/cinder

**Comment by duhow** [comment]
Strange, but cannot access to it.
```
> docker pull rexray/cinder
Trying to pull repository docker.io/rexray/cinder ... 
repository docker.io/rexray/cinder not found: does not exist or no pull access
```

**Comment by clintkitson** [comment]
Check the example commands. These are plugins so you issue docker plugin
install commands.

**Comment by duhow** [comment]
Magnum is using the Rexray image as a container, not plugin:
https://github.com/openstack/magnum/blob/master/magnum/drivers/common/templates/swarm/fragments/volume-service.sh#L52-L65
If I install it as plugin, I still can use **openstack** service instead of **cinder**, or should it migrate to **cinder**?

**Comment by clintkitson** [comment]
The rexray/cinder plugin is continually updated so I would suggest you move
that way.

**Comment by duhow** [comment]
Checked full plugin config, and actually the fields exist:
``` 
"CINDER_AUTHURL=",
"CINDER_USERID=",
"CINDER_USERNAME=",
"CINDER_PASSWORD=",
"CINDER_TRUSTID=",
``` 

But when trying to enable the plugin, another error appears:
```
Error response from daemon: rpc error: code = 2 desc = oci runtime error: flag provided but not defined: -console
```

The Docker version is:
```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      b5e3294/1.13.1
 Built:           Wed Aug 16 13:58:20 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      b5e3294/1.13.1
 Built:           Wed Aug 16 13:58:20 2017
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Comment by clintkitson** [comment]
Can you give the complete example of what command you're issuing that gives this error? The `-console` is definitely not expected.

**Comment by duhow** [comment]
Just `docker plugin install rexray/cinder`, whether I specify settings or not, will display that and not install the plugin.
Using Fedora Atomic 26 CloudImage 20171016.

**Comment by clintkitson** [comment]
Does your `docker` engine work with any container? I did some research on your issue and am finding some interesting results pointing to a bad combination of the engine and runc?

https://github.com/moby/moby/issues/30198

**Comment by duhow** [comment]
I did the same search, but yes, other containers (httpd, ubuntu, centos) are working fine.

**Comment by clintkitson** [comment]
@duhow That is really strange. It looks like it's something with the Atomic builds and Docker. I am not able to launch any Docker plugins whether REX-Ray or not. Can you verify this as well? I get the same error on all plugins.

**Comment by duhow** [comment]
Right, plugins `kuryr/libnetwork2`and `vieux/sshfs` are giving the same error.
So, is there any other way to setup this "plugin" as a container, for example?

**Comment by clintkitson** [comment]
You can give this a shot.

Create REX-Ray Docker managed plugin
```
git clone https://github.com/thecodeteam/rexray
cd rexray
DRIVER=cinder make build-docker-plugin
```
Go into managed plugin build directory, and manually build a standard container
```
cd .docker/plugins/cinder/
docker build -t youruser/rexray-cinder:0.11.0-8 .
```
Update your startup script in magnum or run it manually to test
```
ExecStart=/usr/bin/docker run -d --name=rexray --privileged \\
--pid host \\
--net host \\
-p 7979:7979 \\
-v /run/docker/plugins:/run/docker/plugins \\
-v /var/lib/rexray:/var/lib/rexray:rshared \\
-v /var/log/rexray:/var/log/rexray \\
-v /var/run/rexray:/var/run/rexray \\
-v /var/lib/docker:/var/lib/docker:rshared \\
-v /var/run/docker:/var/run/docker \\
-v /dev:/dev \\
-v /etc/rexray/config.yml:/etc/rexray/config.yml \\
yourrepo/rexray-cinder:0.11.0-8
```

**Comment by duhow** [comment]
When running the container, I'm getting the error:
```
error: service startup failed: libstorage: error authenticating
```
I should expect a Rexray error, but libstorage?

**Comment by clintkitson** [comment]
Libstorage is the package internally that has the cinder driver so that is
normal. Sounds straight forward, check your auth env variables.

**Comment by duhow** [comment]
Ok, checked it, even I set the credentials in `/etc/rexray/config.yml`, I have to pass them as environment (`-e CINDER_AUTHURL, CINDER_USERID, CINDER_PASSWORD` In this case, `CINDER_TRUSTID` is empty).

Now having the error:
```
error: service startup failed: libstorage: error getting newComputeV2
```

**Comment by clintkitson** [comment]
You should turn rexray debugging on and check the containers logs on start.

REXRAY_DEBUG=true

**Comment by duhow** [comment]
It seems it's passing beyond the original container error.
```
info msg=DockerLegacyMode enabled=false time=1509117755318 
debug msg="trapped signals" time=1509117755319 
debug msg="loading config" buildType="client+agent+controller" configFileName=rexray globalConfigFileExists=true globalConfigFilePath="/etc/rexray/rexray.yml" ignoreExists=false time=1509117755320 userConfigFileExists=false userConfigFilePath="/root/.rexray/rexray.yml" 
debug msg="validating global config" buildType="client+agent+controller" configFileName=rexray globalConfigFileExists=true globalConfigFilePath="/etc/rexray/rexray.yml" ignoreExists=false time=1509117755320 userConfigFileExists=false userConfigFilePath="/root/.rexray/rexray.yml" 
debug msg="created new config" buildType="client+agent+controller" configFileName=rexray globalConfigFileExists=true globalConfigFilePath="/etc/rexray/rexray.yml" ignoreExists=false time=1509117755320 userConfigFileExists=false userConfigFilePath="/root/.rexray/rexray.yml" 
debug msg="initializing configuration" 
debug msg="loading yaml for Global" 
debug msg="loading yaml for CSI" 
debug msg="loading global config file" path="/etc/rexray/rexray.yml" 
debug msg="usage template path" path="/root/.rexray/usage.template" time=1509117755323 
debug msg="loaded usage template" source=UsageTemplate time=1509117755323 
debug msg="updating log level" level=debug time=1509117755324 
info msg="updated log level" logLevel=debug 
debug msg="created scoped scope" new=rexray.cli parentScopes="rexray," 
debug msg=os.args time=1509117755329 val=[rexray start --nopid] 
debug msg="host is empty; initiliazing default services" time=1509117755341 
debug msg="libStorage auto service mode disabled; services defined" time=1509117755343 
debug msg="starting embedded libStorage server" time=1509117755343 
debug msg="created scoped scope" new=libstorage.server parentScopes="rexray.cli,rexray," 
info msg="configured logging" libstorage.logging.httpRequests=false libstorage.logging.httpResponses=false libstorage.logging.level=debug server=honey-scale-ht time=1509117755390 
debug msg="parsed server auth property" libstorage.server.auth.disabled=false server=honey-scale-ht time=1509117755403 
debug msg="parsed server auth property" libstorage.server.auth.key= server=honey-scale-ht time=1509117755411 
debug msg="parsed server auth property" libstorage.server.auth.alg=HS256 server=honey-scale-ht time=1509117755416 
debug msg="parsed server auth property" libstorage.server.auth.allow=[] server=honey-scale-ht time=1509117755424 
debug msg="parsed server auth property" libstorage.server.auth.deny=[] server=honey-scale-ht time=1509117755430 
info msg="configured global auth" libstorage.server.auth.alg=HS256 libstorage.server.auth.allow=[] libstorage.server.auth.deny=[] libstorage.server.auth.disabled=false libstorage.server.auth.key= server=honey-scale-ht time=1509117755430 
info msg="initializing server" server=honey-scale-ht time=1509117755431 
info msg="initializing server services" server=honey-scale-ht time=1509117755432 
debug msg="configured result schema validation" enabled=false server=honey-scale-ht time=1509117755436 
debug msg="got services map" count=1 server=honey-scale-ht time=1509117755438 
debug msg="processing service config" server=honey-scale-ht service=cinder time=1509117755438 
debug msg="getting scoped config for service" scope=libstorage.server.services.cinder server=honey-scale-ht service=cinder time=1509117755438 
debug msg="created scoped scope" new=libstorage.server.services.cinder parentScopes="libstorage.server,rexray.cli,rexray," 
debug msg="got driver name" driverName=cinder server=honey-scale-ht service=cinder time=1509117755443 
info msg="service shutdown complete" time=1509117755781 
error: service startup failed: libstorage: error getting newComputeV2
```

**Comment by clintkitson** [comment]
This is either a miscknfugurstion of auth parameters or the service
endpoint that represents the compute in openstack is not properly
registered.

Can you have the openstack admin review the logs?

**Comment by duhow** [comment]
Still looking at this, I'll let you know if there is any progress.
Btw, can you label this issue? Probably more users are affected with this.

**Comment by mazpie** [comment]
Did you manage to solve the issue? Still present on OpenStack Train release
