### ISSUE TITLE
ScaleIO driver limitation of 31 characters for volume name

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/rexray#24]
The ScaleIO platform only allows names up to 31 characters through the platform API.  This means anonymous volumes that get created based on GUIDs don't work properly, ie `-v /path`.

**Comment by clintonskitson** [comment]
Reference this issue https://github.com/emccode/rexray/issues/17

**Comment by akutz** [comment]
Hi @clintonskitson, 

So issue #17 references Docker PR https://github.com/docker/docker/pull/15507 which is merged. Does that mean this issue can be closed? Can #17 be closed?

**Comment by clintonskitson** [comment]
The general problem relating to the mysql container and external volumes was resolved.  But sending the SIO plugin volumes with names >31 characters still causes errors.

**Comment by Oskoss** [comment]
Adding a `+1` to this for the ScaleIO volume name issue. We are trying to create a volume for interacting with cloud foundry by the means of a service broker. Thus we need each volume to have a UUID 32 chars in length. Below is a stack trace for the error fyi.

```
016-03-01 14:52:01,592 [http-nio-443-exec-2] ERROR c.e.s.s.s.ConnectionServiceImpl - Got error from cluster: LONG_NAME
2016-03-01 14:52:01,594 [http-nio-443-exec-2] ERROR c.e.s.s.w.c.RestApiController - Got an exception in handleException
com.emc.s3g.scaleio.services.ScaleIORemoteRuntimeException: The given name exceeds the allowed length of 31 characters.
	at com.emc.s3g.scaleio.services.ConnectionServiceImpl.callSystem(ConnectionServiceImpl.java:250) ~[services-1.0-SNAPSHOT.jar:na]
	at com.emc.s3g.scaleio.services.ConnectionServiceImpl.invokeRequest(ConnectionServiceImpl.java:206) ~[services-1.0-SNAPSHOT.jar:na]
	at com.emc.s3g.scaleio.services.ConnectionServiceImpl.invokeMethod(ConnectionServiceImpl.java:182) ~[services-1.0-SNAPSHOT.jar:na]
	at com.emc.s3g.scaleio.services.RestServiceImpl.sendRequest(RestServiceImpl.java:502) ~[services-1.0-SNAPSHOT.jar:na]
	at com.emc.s3g.scaleio.services.RestServiceImpl.sendRequest(RestServiceImpl.java:460) ~[services-1.0-SNAPSHOT.jar:na]
	at com.emc.s3g.scaleio.services.RestServiceImpl.createObject(RestServiceImpl.java:420) ~[services-1.0-SNAPSHOT.jar:na]
	at com.emc.s3g.scaleio.web.controller.RestApiController.postObject(RestApiController.java:66) ~[RestApiController.class:na]
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215) ~[spring-web-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) ~[spring-web-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745) ~[spring-webmvc-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:685) ~[spring-webmvc-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80) ~[spring-webmvc-3.2.9.RELEASE.jar:3.2.9.RELEASE]
```

**Comment by clintonskitson** [comment]
The ScaleIO platform itself does not allow this. In 0.3.2 we merged a
change that will shrink the volume name down to 31 chars automatically.
When the volume is referenced with a longer name it will always return the
shorter backend volume.

**Comment by codenrhoden** [comment]
Closing due to inactivity.
