### ISSUE TITLE
Can not mount - No such file or directory

### ISSUE THREAD

**Issue by bretif** [codedellemc/rexray#477]
My env:
rexray 0.3.3 (in docker container)
CoreOS stable (1010.5.0)
Openstack

On my coreos server I am able to mount disk but for a specific disk it is failing.
It keeps tells me:

```
FATA[0006] open /dev/vdk: no such file or directory 
```

Example:

```
# rexray volume
- name: grafana-lib
  volumeid: 8d099d2c-8acd-40ae-8cf9-5e337969b616
  availabilityzone: nova
  status: available
  volumetype: classic
  iops: 0
  size: "16"
  networkname: ""
  attachments: []

# rexray volume mount --volumename=grafana-lib
INFO[0000] [linux]                                      
INFO[0000] [docker]                                     
INFO[0000] [openstack]                                  
INFO[0000] storage driver initialized                    availabilityZone=nova domainId= domainName= identityEndpoint=https://auth.cloud.ovh.net/v2.0/ instanceId=6a78cdad-e879-4455-8cc0-938eace68231 moduleName= password=****** provider=Openstack region=GRA1 tenantId= tenantName=5875110575690306 userId= userName=X5CWSTrJZA6c
INFO[0000] os driver initialized                         moduleName= provider=linux
INFO[0000] docker volume driver initialized              availabilityZone= iops= moduleName= provider=docker size= volumeRootPath=/data volumeType=
INFO[0000] vdm.Mount                                     driverName=docker moduleName= newFsType= overwriteFs=false preempt=false volumeID= volumeName=grafana-lib
INFO[0000] mounting volume                               driverName=docker moduleName= newFsType= overwriteFs=false volumeID= volumeName=grafana-lib
INFO[0000] sdm.GetVolume                                 driverName=Openstack moduleName= volumeID= volumeName=grafana-lib
INFO[0001] sdm.GetVolumeAttach                           driverName=Openstack instanceID=6a78cdad-e879-4455-8cc0-938eace68231 moduleName= volumeID=8d099d2c-8acd-40ae-8cf9-5e337969b616
INFO[0001] odm.Unmount                                   driverName=linux moduleName= mountPoint=/var/lib/rexray/volumes/grafana-lib
INFO[0001] sdm.AttachVolume                              driverName=Openstack force=true instanceID=6a78cdad-e879-4455-8cc0-938eace68231 moduleName= runAsync=false volumeID=8d099d2c-8acd-40ae-8cf9-5e337969b616
INFO[0006] odm.GetMounts                                 deviceName=/dev/vdk driverName=linux moduleName= mountPoint=
INFO[0006] odm.Format                                    deviceName=/dev/vdk driverName=linux fsType=ext4 moduleName= overwriteFs=false
FATA[0006] open /dev/vdk: no such file or directory 

# rexray volume
- name: grafana-lib
  volumeid: 8d099d2c-8acd-40ae-8cf9-5e337969b616
  availabilityzone: nova
  status: in-use
  volumetype: classic
  iops: 0
  size: "16"
  networkname: ""
  attachments:
  - volumeid: 8d099d2c-8acd-40ae-8cf9-5e337969b616
    instanceid: 6a78cdad-e879-4455-8cc0-938eace68231
    devicename: /dev/vdk
    status: ""

# rexray volume unmount --volumename=grafana-lib
INFO[0000] [linux]                                      
INFO[0000] [docker]                                     
INFO[0000] [openstack]                                  
INFO[0000] os driver initialized                         moduleName= provider=linux
INFO[0000] storage driver initialized                    availabilityZone=nova domainId= domainName= identityEndpoint=https://auth.cloud.ovh.net/v2.0/ instanceId=6a78cdad-e879-4455-8cc0-938eace68231 moduleName= password=****** provider=Openstack region=GRA1 tenantId= tenantName=5875110575690306 userId= userName=X5CWSTrJZA6c
INFO[0000] docker volume driver initialized              availabilityZone= iops= moduleName= provider=docker size= volumeRootPath=/data volumeType=
INFO[0000] vdm.Unmount                                   driverName=docker moduleName= volumeID= volumeName=grafana-lib
INFO[0000] initialized count                             count=0 moduleName= volumeName=grafana-lib
INFO[0000] unmounting volume                             driverName=docker moduleName= volumeID= volumeName=grafana-lib
INFO[0000] sdm.GetVolume                                 driverName=Openstack moduleName= volumeID= volumeName=grafana-lib
INFO[0001] sdm.GetVolumeAttach                           driverName=Openstack instanceID=6a78cdad-e879-4455-8cc0-938eace68231 moduleName= volumeID=8d099d2c-8acd-40ae-8cf9-5e337969b616
INFO[0002] odm.GetMounts                                 deviceName=/dev/vdk driverName=linux moduleName= mountPoint=
INFO[0002] sdm.DetachVolume                              driverName=Openstack instanceID= moduleName= runAsync=false volumeID=8d099d2c-8acd-40ae-8cf9-5e337969b616
```

The device `/dev/vdk` is not created.
If I try to mount he volume after the unmount if still fails.
After a reboot of the server it still fails on the same disk.
However I can mount other volume without any issues.

I already faced up this issue on other server.
I did not find specific reason when it happens.

Do you know how I can get rid of the "link" between volume and OS device?

Bertrand

**Comment by clintonskitson** [comment]
@bretif Easy first step could be a reboot of the system. You can also try a command like the following:

`echo 1 > /sys/block/dev/vdk/device/delete `

**Comment by bretif** [comment]
@clintonskitson : Hard to believe but after a reboot, I get the same issue, still only on the same disk. The other ones are working properly.

I do not have any /dev/vdk nor  /sys/block/vdk file in my system

so I do not understand why rexray want to mount it on /dev/vdk

If you have any idea....

**Comment by clintonskitson** [comment]
@bretif Take a look at `/proc/partitions` and see if that device is listed there.

There was a bugfix filed recently for something similar with OpenStack. https://github.com/justinclayton/rexray/tree/openstack_volume_attach_fix

https://github.com/emccode/rexray/compare/master...justinclayton:openstack_volume_attach_fix#diff-5945d3d61100bef758cb786946c0d31cR1051

Can you review `ls -laF /dev/disk/by-id/virtio-*`?

**Comment by bretif** [comment]
I tried to mount it again, it failed.
As you will see below rexray report it as attached bit no disk on my system:

```
# rexray volume
- name: grafana-lib
  volumeid: 8d099d2c-8acd-40ae-8cf9-5e337969b616
  availabilityzone: nova
  status: in-use
  volumetype: classic
  iops: 0
  size: "10"
  networkname: ""
  attachments:
  - volumeid: 8d099d2c-8acd-40ae-8cf9-5e337969b616
    instanceid: 6a78cdad-e879-4455-8cc0-938eace68231
    devicename: /dev/vdk
    status: ""

# ls -laF /dev/disk/by-id/virtio-*
lrwxrwxrwx. 1 root root 9 Jun 28 16:03 /dev/disk/by-id/virtio-21cac8de-878d-4579-b -> ../../vdd
lrwxrwxrwx. 1 root root 9 Jun 28 16:57 /dev/disk/by-id/virtio-291f46a3-46cf-401a-9 -> ../../vdi
lrwxrwxrwx. 1 root root 9 Jun 28 16:03 /dev/disk/by-id/virtio-7ab4a466-aa1e-4df2-9 -> ../../vdc
lrwxrwxrwx. 1 root root 9 Jun 28 16:03 /dev/disk/by-id/virtio-a1044c5a-d1d6-43eb-8 -> ../../vdb
lrwxrwxrwx. 1 root root 9 Jun 28 16:09 /dev/disk/by-id/virtio-e762bebe-f5f6-403a-b -> ../../vde

# cat /proc/partitions  |grep vdk
#
```

The bugfix you send seems similar to my issue.
Is there an easy way to compile myself rexray to test this fix?

**Comment by clintonskitson** [comment]
Yes, you can clone the repo and branch into `$GOPATH/src/
github.com/emccode/rexray` and run `make build-linux-amd64`. You should
have Go 1.5+ installed to do so.

**Comment by bretif** [comment]
@clintonskitson I compile rexray succesfully with commit 9c5cf20.
However I can not test it.
rexray crashes

```
./rexray volume
INFO[0000] [linux]                                      
INFO[0000] [docker]                                     
INFO[0000] [openstack]                                  
INFO[0000] docker volume driver initialized              availabilityZone= iops= moduleName= provider=docker size= volumeRootPath=/data volumeType=
INFO[0000] os driver initialized                         moduleName= provider=linux
INFO[0000] storage driver initialized                    availabilityZone=nova domainId= domainName= identityEndpoint=https://auth.cloud.ovh.net/v2.0/ instanceId=6a78cdad-e879-4455-8cc0-938eace68231 moduleName= password=****** provider=Openstack region=GRA1 tenantId= tenantName=5875110575690306 userId= userName=X5CWSTrJZA6c
INFO[0000] sdm.GetVolume 
PANI[0001] runtime error: slice bounds out of range     
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range [recovered]
	panic: (*logrus.Entry) (0x1b56fa0,0xc820324e00)

goroutine 1 [running]:
panic(0x1b56fa0, 0xc820324e00)
	/usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Entry.log(0xc82004c140, 0xc82033af00, 0x0, 0x0, 0x0, 0xc8202f0400, 0x0, 0x0, 0xc820457400, 0xc82033af60, ...)
	/home/bretif/go/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:113 +0x62c
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc82022d260, 0xc82022d348, 0x1, 0x1)
	/home/bretif/go/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/entry.go:169 +0xdf
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.(*Logger).Panic(0xc82004c140, 0xc82022d348, 0x1, 0x1)
	/home/bretif/go/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/logger.go:163 +0xe7
github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus.Panic(0xc82022d348, 0x1, 0x1)
	/home/bretif/go/src/github.com/emccode/rexray/vendor/github.com/Sirupsen/logrus/exported.go:107 +0x41
github.com/emccode/rexray/rexray/cli.(*CLI).Execute.func1()
	/home/bretif/go/src/github.com/emccode/rexray/rexray/cli/cli.go:224 +0x2e0
panic(0x17d1b00, 0xc82000e070)
	/usr/lib/go-1.6/src/runtime/panic.go:426 +0x4e9
github.com/emccode/rexray/rexray/cli.(*CLI).execute.func1()
	/home/bretif/go/src/github.com/emccode/rexray/rexray/cli/cli.go:243 +0xd4
panic(0x17d1b00, 0xc82000e070)
	/usr/lib/go-1.6/src/runtime/panic.go:426 +0x4e9
github.com/emccode/rexray/drivers/storage/openstack.getDeviceNameById(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bretif/go/src/github.com/emccode/rexray/drivers/storage/openstack/openstack.go:1051 +0x215
github.com/emccode/rexray/drivers/storage/openstack.(*driver).GetVolume(0xc8202432c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bretif/go/src/github.com/emccode/rexray/drivers/storage/openstack/openstack.go:384 +0x569
github.com/emccode/rexray/core.(*sdm).GetVolume(0xc820427300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bretif/go/src/github.com/emccode/rexray/core/drivers_storage.go:335 +0x51f
github.com/emccode/rexray/rexray/cli.(*CLI).initVolumeCmds.func3(0xc82024e1c0, 0x2c090c0, 0x0, 0x0)
	/home/bretif/go/src/github.com/emccode/rexray/rexray/cli/cmds_volume.go:57 +0xc9
github.com/emccode/rexray/rexray/cli.(*CLI).initVolumeCmds.func1(0xc820099dc0, 0x2c090c0, 0x0, 0x0)
	/home/bretif/go/src/github.com/emccode/rexray/rexray/cli/cmds_volume.go:24 +0x88
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).execute(0xc820099dc0, 0x2c090c0, 0x0, 0x0, 0x0, 0x0)
	/home/bretif/go/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:534 +0x85a
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).Execute(0xc820098700, 0x0, 0x0)
	/home/bretif/go/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:617 +0x46a
github.com/emccode/rexray/rexray/cli.(*CLI).execute(0xc82024a000)
	/home/bretif/go/src/github.com/emccode/rexray/rexray/cli/cli.go:247 +0x42
github.com/emccode/rexray/rexray/cli.(*CLI).Execute(0xc82024a000)
	/home/bretif/go/src/github.com/emccode/rexray/rexray/cli/cli.go:230 +0x3e
github.com/emccode/rexray/rexray/cli.Execute()
	/home/bretif/go/src/github.com/emccode/rexray/rexray/cli/cli.go:204 +0x25
main.main()
	/home/bretif/go/src/github.com/emccode/rexray/rexray/rexray.go:11 +0x14
```

**Comment by bretif** [comment]
@clintonskitson The problem is really that rexray detect the wrong device.

I now have the issue with another disk.
He tries to mount `/dev/vdk`, however the new disk is mounted on the OS on `/dev/vdi`.
The volume-id of my disk is `volumeid: 3e29967c-20f7-4e33-81e7-dca8c26c060f` and it is mounted on `/dev/vdi`
```
lrwxrwxrwx. 1 root root 9 Jun 29 10:56 /dev/disk/by-id/virtio-3e29967c-20f7-4e33-8 -> ../../vdi
```

**Comment by bretif** [comment]
@clintonskitson I update your code, cf https://github.com/justinclayton/rexray/compare/openstack_volume_attach_fix...bretif:openstack_volume_attach_fix?expand=1

and now everything is working properly, I do not have anymore issues with missing device name.

```
func getDeviceNameById(volumeID string) (string, error) {
        deviceName := ""
        if len(volumeID) > 0 {
                deviceName = fmt.Sprintf("/dev/disk/by-id/virtio-%s", volumeID[:20])
                _, err := os.Stat(deviceName)
                if os.IsNotExist(err) {
                        return "", err
                }
        } else {
                log.Info("volumeID empty")
                return "", fmt.Errorf("volumeID empty")
        }
        log.Info(fmt.Sprintf("Return deviceName %s", deviceName))
        return deviceName, nil
}
```

**Comment by clintonskitson** [comment]
@justinclayton Can you review the thread here for relevance to your fix?
