### ISSUE TITLE
On docker plugin, how to use custon trusted ca certificate?

### ISSUE THREAD

**Issue by sebglon** [codedellemc/rexray#862]
I have seen that i can set trustedCertsFile on this doc: docs/user-guide/config.md

But how can i  set then on docker plugin?

**Comment by akutz** [comment]
Hi @sebglon,

The plug-ins are not meant to access remote libStorage API endpoints, but rather are each a self-contained libStorage client and server. Thus no TLS is necessary. If you're wanting to set the `cacerts` path because you think it is used for **general** TLS, that's incorrect. The property to which you're referring is **only** specific to libStorage client->server communications.

**Comment by akutz** [comment]
Hi @sebglon,

Also, if you want, you can always just place a file at `/etc/libstorage/tls/cacerts`. It will be detected and loaded as the `cacerts` file since that is the default path. However, this will also enable TLS for libStorage client->server communications, and may have unintended consequences (such as enabling TLS without also providing a client/server key pair).

**Comment by clintkitson** [comment]
One more point to support what @akutz is saying. TLS would be beneficial
with plugins when they are communicating separately to a controller. Here
you would use a plugin called `rexray/agent` and separately a plugin called
`rexray/controller`. We intend (through contribution or {code} efforts) to
make other standalone plugins available and also these agent and controller
plugins.

So today you can either 1) use standalone plugins (without TLS) 2) use
REX-Ray outside of plugins with TLS 3) create your own REX plugins that
specify proper paths and parameters.

**Comment by akutz** [comment]
Thank you @clintkitson. @sebglon, the libStorage client->server to which I referred is the same as Clint's statement:

> TLS would be beneficial with plugins when they are communicating separately to a controller. Here you would use a plugin called `rexray/agent` and separately a plugin called `rexray/controller`. 

In the above model the `agent` is the libStorage client and the `controller` is the libStorage server (as it were). 

The reason I'm following up to what Clint added above is to clarify his statement about plug-ins sans TLS:

> So today you can either 1) use standalone plugins (without TLS)

While Clint is accurate in his account above, I just wanted to make sure it was clear that the lack of TLS in REX-Ray managed plug-ins for Docker is not a security issue. The fact is that REX-Ray managed plug-ins today do not have the capability to be configured in a client->remote controller model, rather both the client *and* controller are both operating inside the plug-in container.

**Comment by sebglon** [comment]
Thant i want to make is to use docker pugin cinder with custom authURL with https.
But my https url use custom ca-cert that i have added on my centos trusted ca-certificates.

But i have an PKI error.

**Comment by sebglon** [comment]
#859

**Comment by akutz** [comment]
Hi @sebglon,

In your case the libStorage `cacerts` file will prove of little help. As I said, it's not for general TLS, only for libStorage's own client->server communiques. 

In your case I recommend you edit your Cinder's Dockerfile so that it copies your custom `cacerts` file to the image's trusted certificate file. The REX-Ray Dockerfiles are all Alpine based, so look [here](https://github.com/gliderlabs/docker-alpine/issues/260) for informaiton on how to update Alpine's TLS trusted cert chain with your custom certificate.

**Comment by sebglon** [comment]
this is my error when i call an https cinder server:

```
msg=REX-Ray 
Binary: /usr/bin/rexray" 
Flavor: client+agent+controller" 
SemVer: 0.9.0+11+dirty" 
OsArch: Linux-x86_64" 
Branch: master" 
Commit: e46c4324f52779a8ce0b34647b4bcb85c4b6130a" 
Formed: Wed, 17 May 2017 14:42:21 UTC" 
SemVer: 0.6.0" 
OsArch: Linux-x86_64" 
Branch: (detached from fa055d6" 
Commit: fa055d6da595602715bdfd5541b4aa6d4dcbcbd9" 
Formed: Wed, 17 May 2017 14:41:50 UTC" 
time=\"2017-05-18T07:22:29Z\" level=panic msg=\"runtime error: comparing uncomparable type pkix.Name\" " plugin=b7c1efb1c92cde4cd981cbd017bed5792
panic: runtime error: comparing uncomparable type pkix.Name [recovered]" 
\tpanic: runtime error: comparing uncomparable type pkix.Name [recovered]" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbea9049a9292082a
\tpanic: (*logrus.Entry) (0xaba360,0xc4224d72c0)" 
goroutine 1 [running]:" 
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.Entry.log(0xc420010c80, 0xc422502120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4224d
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/entry.go:113 +0x28c" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b2
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc420a00030, 0xc420a00110, 0x1, 0x1)" plugin=b7c1efb1c92cde4cd981
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/entry.go:169 +0x14b" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b2
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.(*Logger).Panic(0xc420010c80, 0xc420a00110, 0x1, 0x1)" plugin=b7c1efb1c92cde4cd98
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/logger.go:163 +0xc7" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b2
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.Panic(0xc420a00110, 0x1, 0x1)" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b2
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/exported.go:107 +0x4b" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3
github.com/codedellemc/rexray/cli/cli.(*CLI).Execute.func2()" 
\t/go/src/github.com/codedellemc/rexray/cli/cli/cli.go:240 +0xf8" 
panic(0xa26000, 0xc4224fd080)" 
\t/usr/local/go/src/runtime/panic.go:489 +0x2cf" 
github.com/codedellemc/rexray/cli/cli.(*CLI).execute.func1()" 
\t/go/src/github.com/codedellemc/rexray/cli/cli/cli.go:260 +0xa8" 
panic(0xa26000, 0xc4224fd080)" 
\t/usr/local/go/src/runtime/panic.go:489 +0x2cf" 
github.com/codedellemc/rexray/vendor/github.com/akutz/golf.isStructKind(0xc420a00530, 0xc420a003c8, 0xc420a003d0, 0xc4224fd000)" plugin=b7c1efb1c
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/golf.go:391 +0x11d" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbe
github.com/codedellemc/rexray/vendor/github.com/akutz/golf.parseValue(0xc420a00530, 0xc420a1a000, 0xab10a0, 0xc420717500, 0xab10a0)" plugin=b7c1e
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/golf.go:359 +0xa4" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbea
github.com/codedellemc/rexray/vendor/github.com/akutz/golf.fore(0xc422500d40, 0x14, 0xa825a0, 0xc420a1a000, 0xc422502030)" plugin=b7c1efb1c92cde4
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/golf.go:196 +0x71c" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbe
github.com/codedellemc/rexray/vendor/github.com/akutz/golf.fore(0xc4224fce50, 0xf, 0xa71ac0, 0xc422500c20, 0xc422502030)" plugin=b7c1efb1c92cde4c
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/golf.go:219 +0x3bb" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbe
github.com/codedellemc/rexray/vendor/github.com/akutz/golf.fore(0xc4224fcd20, 0xb, 0xa38680, 0xc4224dfef0, 0xc422502030)" plugin=b7c1efb1c92cde4c
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/golf.go:219 +0x3bb" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbe
github.com/codedellemc/rexray/vendor/github.com/akutz/golf.fore(0xacce03, 0x5, 0xa9faa0, 0xc422500c40, 0xc422502030)" plugin=b7c1efb1c92cde4cd981
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/golf.go:219 +0x3bb" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbe
github.com/codedellemc/rexray/vendor/github.com/akutz/golf.Fore(0xacce03, 0x5, 0xa9faa0, 0xc422500c40, 0xc422500c40)" plugin=b7c1efb1c92cde4cd981
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/golf.go:146 +0xbb" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbea
github.com/codedellemc/rexray/vendor/github.com/akutz/golf/logrus.(*TextFormatter).appendKeyValue(0xc42012b340, 0xc42013aa80, 0xacce03, 0x5, 0xa9
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/logrus/text_formatter.go:176 +0xaa" plugin=b7c1efb1c92cde4cd981cbd017bed5792
github.com/codedellemc/rexray/vendor/github.com/akutz/golf/logrus.(*TextFormatter).Format(0xc42012b340, 0xc4224d7200, 0x0, 0xc420a01160, 0x6fcffe
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/akutz/golf/logrus/text_formatter.go:89 +0x481" plugin=b7c1efb1c92cde4cd981cbd017bed5792
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.(*Entry).Reader(0xc4224d7200, 0xc429459202, 0xc4224d7200, 0x0)" plugin=b7c1efb1c9
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/entry.go:44 +0x40" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25b
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.Entry.log(0xc42014f180, 0xc4224dffb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7000102, 0x
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/entry.go:94 +0x11f" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25
github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus.(*Entry).Error(0xc4224d71c0, 0xc4224fc880, 0x1, 0x1)" plugin=b7c1efb1c92cde4cd981
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/Sirupsen/logrus/entry.go:152 +0xd4" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25
github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/context.(*entry).Error(0xc4224fc870, 0xc4224fc880, 0x1, 0x1)" plugin=b
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/context/context_logger.go:228 +0x7c" plugin=b7c1efb1c92cde4c
github.com/codedellemc/rexray/util.activateLibStorage(0xdf85a0, 0xc4201fec00, 0xdf6580, 0xc420265d20, 0xc420265d20, 0x6, 0x0, 0xc4201450e8, 0x0,
\t/go/src/github.com/codedellemc/rexray/util/util_std_controller.go:129 +0xbb4" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbea9049a929
github.com/codedellemc/rexray/util.ActivateLibStorage(0xdf85a0, 0xc4201fec00, 0xdf6580, 0xc420265d20, 0xc4201ec230, 0x0, 0xc420192000, 0xc4200476
\t/go/src/github.com/codedellemc/rexray/util/util.go:429 +0x1ef" 
github.com/codedellemc/rexray/daemon/module.InitializeDefaultModules(0xdf85a0, 0xc4201fec00, 0xdf64a0, 0xc42017f740, 0x0, 0x0, 0x0)" plugin=b7c1e
\t/go/src/github.com/codedellemc/rexray/daemon/module/module.go:147 +0x190" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbea9049a9292082
github.com/codedellemc/rexray/daemon.start(0xdf85a0, 0xc4201fec00, 0xdf64a0, 0xc42017f740, 0xc42015af60, 0x29, 0xc4201fec60, 0x0, 0x0, 0xc4200ba0
\t/go/src/github.com/codedellemc/rexray/daemon/daemon_std_agent.go:21 +0x67" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbea9049a929208
github.com/codedellemc/rexray/daemon.Start(0xdf85a0, 0xc4201fec00, 0xdf64a0, 0xc42017f740, 0xc42015af60, 0x29, 0xc4201fec60, 0x0, 0x0, 0x0)" plug
\t/go/src/github.com/codedellemc/rexray/daemon/daemon.go:27 +0xb1" 
github.com/codedellemc/rexray/cli/cli.(*CLI).startDaemon(0xc420076900)" 
\t/go/src/github.com/codedellemc/rexray/cli/cli/service.go:198 +0x452" 
github.com/codedellemc/rexray/cli/cli.(*CLI).start(0xc420076900)" 
\t/go/src/github.com/codedellemc/rexray/cli/cli/service.go:49 +0x247" 
github.com/codedellemc/rexray/cli/cli.(*CLI).initServiceCmds.func2(0xc4201fd200, 0xc4202653e0, 0x0, 0x2)" plugin=b7c1efb1c92cde4cd981cbd017bed579
\t/go/src/github.com/codedellemc/rexray/cli/cli/cmds_04_service.go:32 +0x2a" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbea9049a929208
github.com/codedellemc/rexray/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201fd200, 0xc420265200, 0x2, 0x2, 0xc4201fd200, 0xc420265200)"
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/spf13/cobra/command.go:648 +0x234" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25b
github.com/codedellemc/rexray/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42006f200, 0xc420047d78, 0xc420047d70, 0xc42015a780)" plugin=b
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/spf13/cobra/command.go:734 +0x339" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25b
github.com/codedellemc/rexray/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42006f200, 0xaf91f0, 0xc4202068d0)" plugin=b7c1efb1c92cde4cd981
\t/go/src/github.com/codedellemc/rexray/vendor/github.com/spf13/cobra/command.go:693 +0x2b" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bf
github.com/codedellemc/rexray/cli/cli.(*CLI).execute(0xc420076900)" 
\t/go/src/github.com/codedellemc/rexray/cli/cli/cli.go:264 +0x4b" 
github.com/codedellemc/rexray/cli/cli.(*CLI).Execute(0xc420076900)" 
\t/go/src/github.com/codedellemc/rexray/cli/cli/cli.go:247 +0x71" 
github.com/codedellemc/rexray/cli/cli.Execute(0xdf85a0, 0xc420052780)" 
\t/go/src/github.com/codedellemc/rexray/cli/cli/cli.go:214 +0x43" 
github.com/codedellemc/rexray/cli/rexray.Run()" 
\t/go/src/github.com/codedellemc/rexray/cli/rexray/rexray.go:102 +0x435" 
main.main()" 
\t/go/src/github.com/codedellemc/rexray/cli/rexray/rexray/rexray-main.go:12 +0x20" plugin=b7c1efb1c92cde4cd981cbd017bed579214ca04e3b25bfcbea9049a
Sending SIGTERM to plugin failed with error: rpc error: code = 2 desc = containerd: container not found"
Sending SIGTERM to plugin failed with error: rpc error: code = 2 desc = containerd: container not found"

```

**Comment by thabach** [comment]
Hey guys - we have another scenario for custom certificates that would benefit us if we could provide the trusted certificate authorities during a plugin install.
 
We would like to install the rexrey s3fs docker plugin in a corporate environment, where all the egress traffic to the internet is made via an HTTP proxy.
 
Additionally to that, our corporate proxy intercepts, for inspection, all the TLS traffic and uses for that our own, company-internal CA certificates. That aspect requires us to update/change the trusted CA certificates on the clients, in order to prevent from TLS handshake errors.
 
Example of the rexray docker plugin we are trying to enable:
`docker plugin install rexray/s3fs S3FS_ACCESSKEY=$S3_ACCESS_KEY S3FS_SECRETKEY=$S3_SECRET_KEY REXRAY_LOGLEVEL=debug`
 
This was failing initially due to the need to define the HTTP_PROXY environment variable - but after talking with  @codenrhoden and his great help we manage to overcome that (also there is now a issue to update that: https://github.com/codedellemc/rexray/issues/933).  But then we faced the TLS handshake problem due to our internal CA certificates not being trusted by the "plugin".
 
We manage to build the plugin from the source and made it work by changing the trusted certificate authorities file ( /etc/ssl/certs/ca-certificates.cer) to include our own CA.
 
It would be great if we could provide our trusted CA file for the plugin to use during the install, without having to build the plugin from the source on our own.
 
That would be great and very much appreciated - Thanks ! 🙏

**Comment by darkl0rd** [comment]
Besides proxies in a corporate network, another, these days also very common use-case would be self-hosted S3 compatible services such as for example Minio. When hosting a minio instance behind https using a certificate signed by an internal CA, one runs into the same problem.

Current workaround:
``` docker plugin install rexray/s3fs ... 
cp ca.pem /var/lib/docker/plugins/<plugin id>/rootfs/etc/ssl/certs
docker plugin enable rexray/s3fs
```

**Comment by gingerbreadassassin** [comment]
Thanks to @darkl0rd for putting me on the right track. I'm using FreeNAS's S3 service, which is done via minio and forces https. I use my pfsense router as my intranet's root CA, and that was already installed on my CentOS box. My commands were:

```
[me@centos ~]$ docker plugin install --disable rexray/s3fs \ 
S3FS_OPTIONS="allow_other,nonempty,use_path_request_style,url=https://freenas-s3-host.domain.local:9000"  \
S3FS_ACCESSKEY="accesskey" S3FS_SECRETKEY="secretkey" \
S3FS_ENDPOINT="https://freenas-s3-host.domain.local:9000" \ 
REXRAY_LOGLEVEL=debug 
--alias s3fs \
--grant-all-permissions
[me@centos ~]$ sudo cp pfsense.crt /var/lib/docker/plugins/$(docker plugin ls --no-trunc | awk '/s3fs/ {print $1}')/rootfs/etc/ssl/certs
[me@centos ~]$ docker plugin enable s3fs:latest
```

It would be really nice to be able to use the docker host's trusted CA, or even just put some kind of notice about this workaround in the docs somewhere. I can't get this afternoon back ☹️
